### PR TITLE
Feature: add StatefulSet templates

### PR DESCRIPTION
**Pull request by GRomR1**
Hi all

I would like add this two useful features
- extract a Pod spec from Deployment to `_pod.tpl` file (don't change anything inside except indenting)
- add a capability to create `StatefulSet` based on this tpl

Inspired by [this](https://github.com/fluent/helm-charts/tree/main/charts/fluentd/templates) chart. 

Also the common sample with name `web-app.values.yml` is great but is complex to understand a base idea and run a simple test.  I add a new two examples that easy to run.

### CODE REVIEW

**Comment by GRomR1** [comment]
@randreev1321 could you pls review this PR?

**Comment by randreev1321** [comment]
Hi @GRomR1.

Thanks for your activity and suggestion. Looks wery nice!

Could you add the usage of the pod template for other workloads as well?

**Comment by randreev1321** [comment]
Think it'll be better to finish this PR before #32

**Comment by GRomR1** [comment]
@randreev1321 
- I've add this definition to cronjob, job, helm-hooks. any other places?
- agree with you, merge this before #32 

helm-hooks and job I can't test, cron-job tested with this command:
```
❯ helm template whoami \
  --values ./samples/cron-jobs.values.yml  \
  ./ | k apply -f - --dry-run=client
cronjob.batch/whoami-flush-cache created (dry run)
cronjob.batch/whoami-mailing created (dry run)
cronjob.batch/whoami-report created (dry run)
```

**Comment by rantanevich** [comment]
By the way, you can also define `helpers.container` template and use it to declare `containers` and `initContainers` in your `helpers.pod`.

**Pull request merged**
